@startuml

class Singelton {
    -Singelton: instance
    -int: score

    -Singelton()

    +getInstance(): Singelton
    +increaseScore(): void
    +getScore(): int

}

class Circus {

}

Circus --> Singelton


@enduml