@startuml StatePattern

class Game {
    - currentGame:GameState
    + setState(GameState) : void
    + currentEvent()
}

interface GameState { 
    +stateAction();
    
}

class BeginGame implements GameState{ 
    +stateAction();
    +startGame();
    +chooseDifficulty();
   
}

class AlmostDoneGame implements GameState{
    +stateAction();
   
}

class FinshedGame implements GameState{   
    +stateAction();
}

Game *-- GameState
@enduml